//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanillaRuleGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesSlim {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesSlim() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VanillaRuleGenerator.Properties.ResourcesSlim", typeof(ResourcesSlim).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///		&lt;title&gt;Keep Talking and Nobody Explodes&lt;/title&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;initial-scale=1&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/normalize.css&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/main.css&quot;&gt;
        ///		&lt;script src=&apos;js/highlighter.js&apos;&gt;&lt;/script&gt;
        ///		&lt;link rel=&apos;stylesheet&apos; type=&apos;text/css&apos; href=&apos;css/font.css&apos;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;div id=&quot;ManualContent&quot;&gt;
        ///			&lt;di [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Capacitor_Discharge {
            get {
                return ResourceManager.GetString("Capacitor_Discharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///		&lt;title&gt;Keep Talking and Nobody Explodes&lt;/title&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;initial-scale=1&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/normalize.css&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/main.css&quot;&gt;
        ///		&lt;script src=&apos;js/highlighter.js&apos;&gt;&lt;/script&gt;
        ///		&lt;link rel=&apos;stylesheet&apos; type=&apos;text/css&apos; href=&apos;css/font.css&apos;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;div id=&quot;ManualContent&quot;&gt;
        ///			&lt;di [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Complicated_Wires {
            get {
                return ResourceManager.GetString("Complicated_Wires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///        &lt;title&gt;Keep Talking and Nobody Explodes&lt;/title&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;initial-scale=1&quot;&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/normalize.css&quot;&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/main.css&quot;&gt;
        ///        &lt;script src=&apos;js/highlighter.js&apos;&gt;&lt;/script&gt;
        ///        &lt;link rel=&apos;stylesheet&apos; type=&apos;text/css&apos; href=&apos;css/font.css&apos;&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///		&lt;title&gt;Keep Talking and Nobody Explodes&lt;/title&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;initial-scale=1&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/normalize.css&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/main.css&quot;&gt;
        ///		&lt;script src=&apos;js/highlighter.js&apos;&gt;&lt;/script&gt;
        ///		&lt;link rel=&apos;stylesheet&apos; type=&apos;text/css&apos; href=&apos;css/font.css&apos;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;div id=&quot;ManualContent&quot;&gt;
        ///			&lt;di [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Keypads {
            get {
                return ResourceManager.GetString("Keypads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///		&lt;title&gt;Keep Talking and Nobody Explodes&lt;/title&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;initial-scale=1&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/normalize.css&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/main.css&quot;&gt;
        ///		&lt;script src=&apos;js/highlighter.js&apos;&gt;&lt;/script&gt;
        ///		&lt;link rel=&apos;stylesheet&apos; type=&apos;text/css&apos; href=&apos;css/font.css&apos;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;div id=&quot;ManualContent&quot;&gt;
        ///			&lt;di [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Knobs {
            get {
                return ResourceManager.GetString("Knobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///		&lt;title&gt;Keep Talking and Nobody Explodes&lt;/title&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;initial-scale=1&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/normalize.css&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/main.css&quot;&gt;
        ///		&lt;script src=&apos;js/highlighter.js&apos;&gt;&lt;/script&gt;
        ///		&lt;link rel=&apos;stylesheet&apos; type=&apos;text/css&apos; href=&apos;css/font.css&apos;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;div id=&quot;ManualContent&quot;&gt;
        ///			&lt;di [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Mazes {
            get {
                return ResourceManager.GetString("Mazes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///		&lt;title&gt;Keep Talking and Nobody Explodes&lt;/title&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;initial-scale=1&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/normalize.css&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/main.css&quot;&gt;
        ///		&lt;script src=&apos;js/highlighter.js&apos;&gt;&lt;/script&gt;
        ///		&lt;link rel=&apos;stylesheet&apos; type=&apos;text/css&apos; href=&apos;css/font.css&apos;&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;div id=&quot;ManualContent&quot;&gt;
        ///			&lt;di [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Memory {
            get {
                return ResourceManager.GetString("Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///		&lt;title&gt;Keep Talking and Nobody Explodes&lt;/title&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;initial-scale=1&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/normalize.css&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/main.css&quot;&gt;
        ///		&lt;link rel=&apos;stylesheet&apos; type=&apos;text/css&apos; href=&apos;css/font.css&apos;&gt;
        ///		&lt;script src=&apos;js/highlighter.js&apos;&gt;&lt;/script&gt;
        ///		&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;div id=&quot;ManualContent&quot;&gt;
        ///			&lt;d [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Morse_Code {
            get {
                return ResourceManager.GetString("Morse_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///		&lt;title&gt;Passwords — Keep Talking and Nobody Explodes Module&lt;/title&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;initial-scale=1&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/normalize.css&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/main.css&quot;&gt;
        ///		&lt;link rel=&apos;stylesheet&apos; type=&apos;text/css&apos; href=&apos;css/font.css&apos;&gt;
        ///		&lt;script src=&apos;js/highlighter.js&apos;&gt;&lt;/script&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;div id=&quot;Manu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Passwords {
            get {
                return ResourceManager.GetString("Passwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///		&lt;title&gt;Simon Says — Keep Talking and Nobody Explodes Module&lt;/title&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;initial-scale=1&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/normalize.css&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/main.css&quot;&gt;
        ///		&lt;link rel=&apos;stylesheet&apos; type=&apos;text/css&apos; href=&apos;css/font.css&apos;&gt;
        ///		&lt;script src=&apos;js/highlighter.js&apos;&gt;&lt;/script&gt;
        ///	&lt;body&gt;
        ///		&lt;div id=&quot;ManualContent [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Simon_Says {
            get {
                return ResourceManager.GetString("Simon_Says", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///		&lt;title&gt;The Button — Keep Talking and Nobody Explodes Module&lt;/title&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;initial-scale=1&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/normalize.css&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/main.css&quot;&gt;
        ///		&lt;link rel=&apos;stylesheet&apos; type=&apos;text/css&apos; href=&apos;css/font.css&apos;&gt;
        ///		&lt;script src=&apos;js/highlighter.js&apos;&gt;&lt;/script&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;div id=&quot;Man [rest of string was truncated]&quot;;.
        /// </summary>
        public static string The_Button {
            get {
                return ResourceManager.GetString("The_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///		&lt;title&gt;Venting Gas — Keep Talking and Nobody Explodes Module&lt;/title&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;initial-scale=1&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/normalize.css&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/main.css&quot;&gt;
        ///		&lt;link rel=&apos;stylesheet&apos; type=&apos;text/css&apos; href=&apos;css/font.css&apos;&gt;
        ///		&lt;script src=&apos;js/highlighter.js&apos;&gt;&lt;/script&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;div id=&quot;Ma [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Venting_Gas {
            get {
                return ResourceManager.GetString("Venting_Gas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///		&lt;title&gt;Who&apos;s on First — Keep Talking and Nobody Explodes Module&lt;/title&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;initial-scale=1&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/normalize.css&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/main.css&quot;&gt;
        ///		&lt;link rel=&apos;stylesheet&apos; type=&apos;text/css&apos; href=&apos;css/font.css&apos;&gt;
        ///		&lt;script src=&apos;js/highlighter.js&apos;&gt;&lt;/script&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;div id= [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Whos_on_First {
            get {
                return ResourceManager.GetString("Whos_on_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///		&lt;title&gt;Wire Sequences — Keep Talking and Nobody Explodes Module&lt;/title&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;initial-scale=1&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/normalize.css&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/main.css&quot;&gt;
        ///		&lt;link rel=&apos;stylesheet&apos; type=&apos;text/css&apos; href=&apos;css/font.css&apos;&gt;
        ///		&lt;script src=&apos;js/highlighter.js&apos;&gt;&lt;/script&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;div id= [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Wire_Sequences {
            get {
                return ResourceManager.GetString("Wire_Sequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///		&lt;title&gt;Wires — Keep Talking and Nobody Explodes Module&lt;/title&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;initial-scale=1&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/normalize.css&quot;&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/main.css&quot;&gt;
        ///		&lt;link rel=&apos;stylesheet&apos; type=&apos;text/css&apos; href=&apos;css/font.css&apos;&gt;
        ///		&lt;script src=&apos;js/highlighter.js&apos;&gt;&lt;/script&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;div id=&quot;ManualCo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Wires {
            get {
                return ResourceManager.GetString("Wires", resourceCulture);
            }
        }
    }
}
