using System.Collections.Generic;
using System.Drawing;
using VanillaRuleGenerator.Properties;

namespace VanillaRuleGenerator.Rules
{
    public class SymbolPool
    {
        public static string GetFileName(string symbol)
        {
            return SymbolPool.FileMap[symbol];
        }

        public static Bitmap GetImage(string symbol)
        {
            return ImageMap[symbol];
        }

        public static List<string> Symbols = new List<string>
        {
            "©","★","☆","ټ","Җ","Ω","Ѭ",
            "Ѽ","ϗ","ϫ","Ϭ","Ϟ","Ѧ","ӕ","Ԇ",
            "Ӭ",/*"҈"*/"◌","Ҋ","ѯ","¿","¶","Ͼ","Ͽ",
            "Ψ","Ѫ","Ҩ","҂","Ϙ","ζ","ƛ","ѣ"
        };

        public static Dictionary<string, string> FileMap = new Dictionary<string, string>
        {
            {
                "©",
                "1-copyright.png"
            },
            {
                "★",
                "2-filledstar.png"
            },
            {
                "☆",
                "3-hollowstar.png"
            },
            {
                "ټ",
                "4-smileyface.png"
            },
            {
                "Җ",
                "5-doublek.png"
            },
            {
                "Ω",
                "6-omega.png"
            },
            {
                "Ѭ",
                "7-squidknife.png"
            },
            {
                "Ѽ",
                "8-pumpkin.png"
            },
            {
                "ϗ",
                "9-hookn.png"
            },
            {
                "ϫ",
                "10-teepee.png"
            },
            {
                "Ϭ",
                "11-six.png"
            },
            {
                "Ϟ",
                "12-squigglyn.png"
            },
            {
                "Ѧ",
                "13-at.png"
            },
            {
                "ӕ",
                "14-ae.png"
            },
            {
                "Ԇ",
                "15-meltedthree.png"
            },
            {
                "Ӭ",
                "16-euro.png"
            },
            {
                /*"҈"*/"◌",
                "17-circle.png"
            },
            {
                "Ҋ",
                "18-nwithhat.png"
            },
            {
                "ѯ",
                "19-dragon.png"
            },
            {
                "¿",
                "20-questionmark.png"
            },
            {
                "¶",
                "21-paragraph.png"
            },
            {
                "Ͼ",
                "22-rightc.png"
            },
            {
                "Ͽ",
                "23-leftc.png"
            },
            {
                "Ψ",
                "24-pitchfork.png"
            },
            {
                "Ѫ",
                "25-tripod.png"
            },
            {
                "Ҩ",
                "26-cursive.png"
            },
            {
                "҂",
                "27-tracks.png"
            },
            {
                "Ϙ",
                "28-balloon.png"
            },
            {
                "ζ",
                "29-weirdnose.png"
            },
            {
                "ƛ",
                "30-upsidedowny.png"
            },
            {
                "ѣ",
                "31-bt.png"
            }
        };

        public static Dictionary<string, Bitmap> ImageMap = new Dictionary<string, Bitmap>
        {
            {
                "©",
                Resources._1_copyright
            },
            {
                "★",
                Resources._2_filledstar
            },
            {
                "☆",
                Resources._3_hollowstar
            },
            {
                "ټ",
                Resources._4_smileyface
            },
            {
                "Җ",
                Resources._5_doublek
            },
            {
                "Ω",
                Resources._6_omega
            },
            {
                "Ѭ",
                Resources._7_squidknife
            },
            {
                "Ѽ",
                Resources._8_pumpkin
            },
            {
                "ϗ",
                Resources._9_hookn
            },
            {
                "ϫ",
                Resources._10_teepee
            },
            {
                "Ϭ",
                Resources._11_six
            },
            {
                "Ϟ",
                Resources._12_squigglyn
            },
            {
                "Ѧ",
                Resources._13_at
            },
            {
                "ӕ",
                Resources._14_ae
            },
            {
                "Ԇ",
                Resources._15_meltedthree
            },
            {
                "Ӭ",
                Resources._16_euro
            },
            {
                /*"҈"*/"◌",
                Resources._17_circle
            },
            {
                "Ҋ",
                Resources._18_nwithhat
            },
            {
                "ѯ",
                Resources._19_dragon
            },
            {
                "¿",
                Resources._20_questionmark
            },
            {
                "¶",
                Resources._21_paragraph
            },
            {
                "Ͼ",
                Resources._22_rightc
            },
            {
                "Ͽ",
                Resources._23_leftc
            },
            {
                "Ψ",
                Resources._24_pitchfork
            },
            {
                "Ѫ",
                Resources._25_tripod
            },
            {
                "Ҩ",
                Resources._26_cursive
            },
            {
                "҂",
                Resources._27_tracks
            },
            {
                "Ϙ",
                Resources._28_balloon
            },
            {
                "ζ",
                Resources._29_weirdnose
            },
            {
                "ƛ",
                Resources._30_upsidedowny
            },
            {
                "ѣ",
                Resources._31_bt
            }
        };
    }
}
